dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=pyitm/
after_success:
  - coveralls
